//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Royal_Project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_order_view
    {
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string u_contact { get; set; }
        public int in_id { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<int> o_fk_pro { get; set; }
        public string pro_name { get; set; }
        public Nullable<int> o_qty { get; set; }
        public Nullable<int> o_unitprice { get; set; }
        public Nullable<double> o_bill { get; set; }
    }
}
