//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Royal_Project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int ID { get; set; }
        public string cname { get; set; }
        public string cmobile { get; set; }
        public string cemail { get; set; }
        public string cquery { get; set; }
    }
}
