//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Royal_Project_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RoyalProjectEntities : DbContext
    {
        public RoyalProjectEntities()
            : base("name=RoyalProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminn> adminns { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<order_table> order_table { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_invoice> tbl_invoice { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<admin_order_view> admin_order_view { get; set; }
    
        public virtual ObjectResult<GetChart_Result> GetChart()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetChart_Result>("GetChart");
        }
    }
}
